require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

# Specify the Xcode project to avoid ambiguity
project 'hicarwork.xcodeproj'

$FirebaseSDKVersion = '10.7.0'
target 'hicarwork' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  flags = get_default_flags()
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  target 'hicarworkTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    # Fix iOS deployment target for all pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
        # Fix boost unary_function error for C++17
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION=1'
        # Disable bitcode (no longer supported by Apple)
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end

    # Strip bitcode from hermes framework
    hermes_path = "#{installer.sandbox.root}/hermes-engine/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64/hermes.framework/hermes"
    if File.exist?(hermes_path)
      system("xcrun bitcode_strip -r #{hermes_path} -o #{hermes_path}")
    end

    react_native_post_install(installer,
                                             # Set `mac_catalyst_enabled` to `true` in order to apply patches
                                             # necessary for Mac Catalyst builds
                                             :mac_catalyst_enabled => false
                                             )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end